export const employee = [
  {
    CNIC: Math.random().toString(),
    Image: require('../assets/emp1.jpg'),
    Name: 'Waleed Butt',
    Age: 22,
    Qualification: 'BCS',
    HomeTown: 'Murree',
    Address: 'House # 448, Street 29, D-12/3',
    City: 'Islamabad',
    Email: 'waleed3072@gmail.com',
    Phone: 923481231123,
  },
  {
    CNIC: Math.random().toString(),
    Image: require('../assets/emp2.jpg'),
    Name: 'Talha Ejaz',
    Age: 21,
    Qualification: 'BCS',
    HomeTown: 'Murree',
    Address: 'House # 26, Street 36, Jinnah Garden',
    City: 'Islamabad',
    Email: 'jhgjh12312312@gmail.com',
    Phone: 966123123123,
  },
  {
    CNIC: Math.random().toString(),
    Image: require('../assets/emp4.jpg'),
    Name: 'Umar Khalid',
    Age: 22,
    Qualification: 'BCS',
    HomeTown: 'Punjab',
    Address: 'House # 123, Street 45',
    City: 'Rawalpindi',
    Email: 'uyhg1jg22@gmail.com',
    Phone: 91987987897,
  },
  {
    CNIC: Math.random().toString(),
    Image: require('../assets/emp3.jpg'),
    Name: 'Talha Malik',
    Age: 30,
    Qualification: 'PHD',
    HomeTown: 'Bangladesh',
    Address: 'House # 789, Street 1011',
    City: 'Rawalpindi',
    Email: 'gfjh1gjh1gjhg@gmail.com',
    Phone: 966876876876,
  },
];
