export const products = [
  {
    key: Math.random().toString(),
    Image: require('../assets/iphonexdesign-800x669.jpg'),
    Name: 'Iphone X',
    Price: 1000,
    Ram: 4,
    Storage: 64,
    Screen: '1920x1080',
    FingerPrint: 'Yes',
  },
  {
    key: Math.random().toString(),
    Image: require('../assets/akrales_190913_3666_0391.jpg'),
    Name: 'Iphone 11',
    Price: 1200,
    Ram: 4,
    Storage: 128,
    Screen: '1440x1080',
    FingerPrint: 'No',
  },
  {
    key: Math.random().toString(),
    Image: require('../assets/kpoSe2Jmn4ghwMAxnBtdid.jpg'),
    Name: 'Galaxy S20',
    Price: 1400,
    Ram: 6,
    Storage: 128,
    Screen: '3840x1440',
    FingerPrint: 'Yes',
  },
  {
    key: Math.random().toString(),
    Image: require('../assets/Samsung-Note-8-Profile-Page.webp'),
    Name: 'Galaxy Note',
    Price: 1400,
    Ram: 6,
    Storage: 128,
    Screen: '1920x1080',
    FingerPrint: 'Yes',
  },
];
