var bookName = 'Angular UI Development';
var version = 2;
var isCompleted = false;
var frameworks1 = ['Angular', 'React', 'Ember'];
var frameworks2 = ['Angular', 'React', 'Ember'];
var Framework;
(function (Framework) {
    Framework[Framework["Angular"] = 0] = "Angular";
    Framework[Framework["React"] = 1] = "React";
    Framework[Framework["Ember"] = 2] = "Ember";
})(Framework || (Framework = {}));
;
var f = Framework.Angular;
var eventId = 7890;
eventId = 'event1';
var myCollection = ['value1', 100, 'test', true];
myCollection[2] = false;
console.log('bookName: ' + bookName);
console.log('version: ' + version);
console.log('isCompleted: ' + isCompleted);
console.log('frameworks1: ' + frameworks1);
console.log('frameworks2: ' + frameworks2);
console.log('Framework: ' + Framework);
console.log('f: ' + f);
console.log('eventId: ' + eventId);
console.log('myCollection: ' + myCollection);
console.log('myCollection[2]: ' + myCollection[2]);
